version: '3.1'
services:
  app:
    container_name: assignmentbackend
    image: assignmentbackend
    build: ./
    ports:
      - "8098:8098"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=4544008
      - POSTGRES_USER=comodo
      - POSTGRES_DB=comodo